// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHN0g5GAS3UKTsrMXUxmrPaj85F_BNQY',
    appId: '1:552609037029:web:c0cc3a525d83d72b9e720c',
    messagingSenderId: '552609037029',
    projectId: 'evently-app-ca19f',
    authDomain: 'evently-app-ca19f.firebaseapp.com',
    storageBucket: 'evently-app-ca19f.firebasestorage.app',
    measurementId: 'G-KSGH2Z3CRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOdrS6A80S_ajZSNcIWgjCevBhFC5fsFo',
    appId: '1:552609037029:android:90bdb08aff8b58039e720c',
    messagingSenderId: '552609037029',
    projectId: 'evently-app-ca19f',
    storageBucket: 'evently-app-ca19f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArVV9vqfjyM-f8-ZbQU1u0TSrw-Zabha4',
    appId: '1:552609037029:ios:8eee9ee3d83580e29e720c',
    messagingSenderId: '552609037029',
    projectId: 'evently-app-ca19f',
    storageBucket: 'evently-app-ca19f.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArVV9vqfjyM-f8-ZbQU1u0TSrw-Zabha4',
    appId: '1:552609037029:ios:8eee9ee3d83580e29e720c',
    messagingSenderId: '552609037029',
    projectId: 'evently-app-ca19f',
    storageBucket: 'evently-app-ca19f.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRHN0g5GAS3UKTsrMXUxmrPaj85F_BNQY',
    appId: '1:552609037029:web:7c96a0d61bfb92d89e720c',
    messagingSenderId: '552609037029',
    projectId: 'evently-app-ca19f',
    authDomain: 'evently-app-ca19f.firebaseapp.com',
    storageBucket: 'evently-app-ca19f.firebasestorage.app',
    measurementId: 'G-DSFWE4HSYC',
  );

}