// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-gxvPde6ugiCTd2ZAB6UBTndwz7Jj9Go',
    appId: '1:463268163851:web:79104125b6b621b84fb20e',
    messagingSenderId: '463268163851',
    projectId: 'evently-app-f353c',
    authDomain: 'evently-app-f353c.firebaseapp.com',
    storageBucket: 'evently-app-f353c.firebasestorage.app',
    measurementId: 'G-3GE2VMNGJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8fd3AM8MZsS8pvdX4LW1qzMi-nHyC-MI',
    appId: '1:463268163851:android:19c2a7ff1e265e8e4fb20e',
    messagingSenderId: '463268163851',
    projectId: 'evently-app-f353c',
    storageBucket: 'evently-app-f353c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxrjpwdQk-s73ABJKOpSc0HEA-g_NTRs',
    appId: '1:463268163851:ios:f58bbed85a73deb74fb20e',
    messagingSenderId: '463268163851',
    projectId: 'evently-app-f353c',
    storageBucket: 'evently-app-f353c.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxrjpwdQk-s73ABJKOpSc0HEA-g_NTRs',
    appId: '1:463268163851:ios:f58bbed85a73deb74fb20e',
    messagingSenderId: '463268163851',
    projectId: 'evently-app-f353c',
    storageBucket: 'evently-app-f353c.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-gxvPde6ugiCTd2ZAB6UBTndwz7Jj9Go',
    appId: '1:463268163851:web:422b4e304fbc3e514fb20e',
    messagingSenderId: '463268163851',
    projectId: 'evently-app-f353c',
    authDomain: 'evently-app-f353c.firebaseapp.com',
    storageBucket: 'evently-app-f353c.firebasestorage.app',
    measurementId: 'G-D7V6BP9PTM',
  );
}
